In [11]:
import os
import pymysql
import pandas as pd

host ='127.0.0.1'
port ='3306'
user ='root'
password=''
database = 'classicmodels'

conn = pymysql.connect(
    host=host,
    port=int(port),
    user=user,
    passwd=password,
    db=database,
    charset='utf8mb4')

def run(sql):
    df = pd.read_sql_query(sql,conn)
    return df

AttributeError: 'NoneType' object has no attribute 'encoding'

In [9]:
run("SHOW TABLES")

DatabaseError: Execution failed on sql: SHOW TABLES
(0, '')
unable to rollback

In [8]:
run("SELECT * FROM products")

DatabaseError: Execution failed on sql: SELECT * FROM products
(0, '')
unable to rollback